name: Build AnchorAI APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '7.5.1'      # use Gradle 7.5.1 for Android 7.2.0 plugin
        cache-disabled: true




    - name: Build release APK
      run: gradle assembleRelease -x lintVitalRelease -x lintVitalReportRelease



    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnchorAI-release-apk
        path: app/build/outputs/apk/release/app-release.apk

