name: Build AnchorAI APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3   # installs Gradle for you :contentReference[oaicite:0]{index=0}

    - name: Build release APK
      run: gradle assembleRelease


    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnchorAI-release-apk
        path: app/build/outputs/apk/release/app-release.apk

