name: Build AnchorAI APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnchorAI-release-apk
        path: app/build/outputs/apk/release/app-release.apk

